### PR TITLE
MSVC compatibility

### LINKED ISSUE #5: Compiling on Windows
I am trying to compile this on windows.
Got all the tools setup like cmake and make but having some rudimentary compile issues.

- How/Where do I add TinyXML2 to the build folder ?, does it need the sources or the compiled lib.
- Once I run cmake it sets up everything in build folder apart from a MakeFile, i.e. make doesn't have anything to run against.

Sorry for these pretty simple build issues, I promise to try and contribute anything I learn about the windows build.

### PR DESCRIPTION
**Pull request by cvuchener**
fix #5

still missing import/export symbol for shared library and getopt configuration

I can build using vcpkg's getopt but it does not have a cmake find_package script. I am using the following changes:
```diff
diff --git a/src/tools/CMakeLists.txt b/src/tools/CMakeLists.txt
index 262d63e..bd2ec17 100644
--- a/src/tools/CMakeLists.txt
+++ b/src/tools/CMakeLists.txt
@@ -1,12 +1,19 @@
 cmake_minimum_required(VERSION 3.12)
 project(hidpp_tools)

+add_library(getopt SHARED IMPORTED)
+set_target_properties(getopt PROPERTIES
+       IMPORTED_LOCATION "D:\\vcpkg\\packages\\getopt-win32_x64-windows\\bin\\getopt.dll"
+       IMPORTED_IMPLIB "D:\\vcpkg\\packages\\getopt-win32_x64-windows\\lib\\getopt.lib"
+       INTERFACE_INCLUDE_DIRECTORIES "D:\\vcpkg\\packages\\getopt-win32_x64-windows\\include")
+
 include_directories(../libhidpp)

 add_library(common OBJECT
        common/common.cpp
        common/Option.cpp
        common/CommonOptions.cpp)
+target_link_libraries(common PUBLIC getopt)

 add_executable(hidpp-check-device hidpp-check-device.cpp)
 target_link_libraries(hidpp-check-device hidpp common Threads::Threads)
diff --git a/src/tools/common/Option.cpp b/src/tools/common/Option.cpp
index ebf3ee7..73dabf0 100644
--- a/src/tools/common/Option.cpp
+++ b/src/tools/common/Option.cpp
@@ -1,11 +1,12 @@
 #include "Option.h"

+#include <sstream>
+#include <map>
+
 extern "C" {
 #include <getopt.h>
 }

-#include <sstream>
-#include <map>

 Option::Option (char short_opt,
                const char *long_opt,
@@ -67,7 +68,7 @@ bool Option::processOptions (int argc, char *argv[],
                longopt.val = 256 + i;
                longopts.push_back (longopt);
        }
-       longopts.emplace_back ((struct option) {});
+       longopts.emplace_back (struct option {});

        int opt;
        while (-1 != (opt = getopt_long (argc, argv,
```
I obviously cannot keep an imported target like that. For some reason including getopt before the standard library headers breaks them.

### CODE REVIEW

**Comment by mcuee** [comment]
Is it possible to include getopt and not to rely on vcpkg. That way you have more control and will not encounter support issues in the future.

**Comment by cvuchener** [comment]
I don't mind replacing getopt with another library. If I have to add a dependency, I might as well use a better parser. I looked at [boost's program_options](https://www.boost.org/doc/libs/1_58_0/doc/html/program_options.html), but I don't like it. [CLI11](https://github.com/CLIUtils/CLI11) is much better, but I'm missing a way to mimic getopt's optional arguments (mainly used for `-v` `--verbose`). I may have to change the syntax if I use it.

**Comment by mcuee** [comment]
The latest commits seems to be good, tested with VS2019 and CMake 3.20.2.

Only problem: if I enable shared dll build, the tools build will fail, something like the following.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\libhidpp\Release\hidpp.lib'	hidpp-check-device	C:\work\hid\hidpp_msvc\build\src\tools\LINK	1	
```

**Comment by cvuchener** [comment]
I know shared library is not working.

> still missing import/export symbol for shared library

You could try `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` but it is not enough, some symbols are still missing. I tried using [GenerateExportHeader](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) and exporting the missing symbols explicitly but it is breaking MSYS2's mingw builds.

**Comment by cvuchener** [comment]
I'm abandoning the support for MSVC shared library with this PR. MSVC users will have to be content with static linking for now. At least you don't have the copy the dll to compensate the lack of rpath.

**Pull request merged**
